(function(){
 function q(){return new URLSearchParams(location.search)}
 function page(){const p=location.pathname.replace(/^\/+|\/+$/g,'')||'home';return p}
 const icons={city:'/assets/icons/nav/city.png',pirat:'/assets/icons/nav/pirat.png',ship:'/assets/icons/nav/upgrade.png',shop:'/assets/icons/nav/upgrade.png',market:'/assets/icons/nav/box.jpg',bank:'/assets/icons/bank_big.png',mail:'/assets/icons/nav/mail.jpg',quest:'/assets/icons/nav/quest.jpg',collection:'/assets/icons/nav/colect.jpg',profession:'/assets/icons/nav/profi.jpg',settings:'/assets/icons/nav/set.jpg',sea:'/assets/icons/nav/map.png'};
 const img=k=>`<img class="tile-icon" src="${assetUrl(icons[k]||k)}">`;
 function cards(items){return `<div class="cards">${items.map(x=>`<a class="card" href="${x.href}">${img(x.icon)}<strong>${SW_UI.esc(x.title)}</strong><small>${SW_UI.esc(x.text||'')}</small></a>`).join('')}</div>`}
 function home(){return `<section class="hero"><img src="${assetUrl('/assets/pic/art/sunduk_old.jpg')}"><div><h1>Онлайн игра Пираты</h1><p>Реконструкция интерфейса по сохранённому дампу.</p><a class="btn" href="/reg/">Регистрация</a> <a class="btn" href="/auth/">Авторизация</a></div></section>`}
 function city(){return `<section class="panel"><h1>Город Толедо</h1><p>Матрос <b>${SW_UI.esc(SW_STORE.get().login)}</b>, ${SW_STORE.get().level} уровень.</p></section>${cards([{icon:'sea',title:'Море',href:'/sea/',text:'Выход в море'},{icon:'ship',title:'Мой корабль',href:'/ship/',text:'Корабль и оснащение'},{icon:'shop',title:'Верфь',href:'/shop/',text:'Корабли и вооружение'},{icon:'market',title:'Рынок',href:'/market/',text:'Торговля ресурсами'},{icon:'bank',title:'Банк',href:'/bank/',text:'Золото и пирастры'},{icon:'quest',title:'Квесты',href:'/quests/',text:'Задания'},{icon:'collection',title:'Коллекции',href:'/collections/',text:'Коллекции'},{icon:'profession',title:'Профессия',href:'/profession/',text:'Профессия'},{icon:'settings',title:'Настройки',href:'/settings/',text:'Профиль и безопасность'}])}`}
 function profile(){const s=SW_STORE.get();return `<section class="profile panel"><img class="avatar" src="${assetUrl('/assets/pic/avatar/sex_1.jpg')}"><div><h1>Матрос ${SW_UI.esc(s.login)}</h1><p>${s.level} уровень · Ранг: Молодой</p><p>Сила ${s.power} · Защита ${s.defense} · Жизнь ${s.hp}/${s.maxHp} · Скорость ${s.speed}</p></div></section>${cards([{icon:'quest',title:'Квесты',href:'/quests/'},{icon:'collection',title:'Коллекции',href:'/collections/'},{icon:'profession',title:'Профессия',href:'/profession/'},{icon:'mail',title:'Почта',href:'/mail/'},{icon:'settings',title:'Настройки',href:'/settings/'}])}`}
 function sea(){const e=SW_SEA.state();const s=SW_STORE.get();return `<section class="sea panel"><div class="sea-bg"><h1>Море</h1><p>Погода: ясная · ${s.invisible?'Невидимость активна':'Видимость обычная'}</p><div class="enemy"><h2>Противник</h2><div class="bar"><i style="width:${e.hp/e.maxHp*100}%"></i></div><p>${e.hp}/${e.maxHp} HP</p></div><div class="actions"><button data-action="fire">Огонь</button><button data-action="board">Абордаж</button><button data-action="invis">Невидимость</button><button data-action="heal">Ремонт</button></div></div></section>`}
 function simple(title, text, links=[]){return `<section class="panel"><h1>${SW_UI.esc(title)}</h1><p>${SW_UI.esc(text)}</p><div class="actions">${links.map(x=>`<a class="btn" href="${x[0]}">${x[1]}</a>`).join('')}</div></section>`}
 function shop(){return simple('Верфь','Корабли, пушки, гарпуны, мортиры, паруса, броня и спутники.',[['/shop/?cmd=ships','Корабли'],['/shop/?cmd=guns','Пушки'],['/shop/?cmd=armor','Броня'],['/shop/?cmd=satellite','Спутник']])}
 function market(){return simple('Рынок','Торговля ресурсами, пирастрами и артефактами.',[['/market/?cmd=res','Ресурсы'],['/market/?cmd=art','Артефакты'],['/market/?cmd=table','Таблица']])}
 function bank(){return simple('Банк','Операции с золотом.',[['/bank/?op=deposit','Положить 100'],['/city/','В город']])}
 function day(){const s=SW_STORE.get();return `<section class="panel gift"><img src="${assetUrl('/assets/pic/art/sunduk_old.jpg')}"><h1>Ежедневный подарок</h1><p>Золото: ${s.money}. Сундук: ${s.dailyClaimed?'получен':'доступен'}.</p><button data-action="claim">Получить подарок</button></section>`}
 function settings(){return simple('Настройки','Локальный профиль и перенос прогресса.',[['/settings/?cmd=reset','Сбросить']])+'<section class="panel"><button data-action="logout">Выйти</button><button data-action="reset">Сбросить прогресс</button></section>'}
 function auth(reg){return `<section class="panel form"><h1>${reg?'Регистрация':'Авторизация'}</h1><input id="login" placeholder="Логин" value="${SW_UI.esc(SW_STORE.get().login)}"><input id="password" type="password" placeholder="Пароль"><button id="submit">${reg?'Создать персонажа':'Войти'}</button></section><script>(function(){document.getElementById('submit').onclick=function(){let s=SW_STORE.get();s.login=document.getElementById('login').value||'Пират';s.password=document.getElementById('password').value||'';SW_STORE.save(s);location.href='/city/'}})();</script>`}
 function render(){let p=page(), title=p==='home'?'Пираты':p;let body=p==='home'?home():p==='city'?city():p==='user'?profile():p==='sea'?sea():p==='shop'?shop():p==='market'?market():p==='bank'?bank():p==='day_prize'?day():p==='settings'?settings():p==='reg'?auth(true):p==='auth'?auth(false):simple(title,'Раздел реконструирован по данным дампа.',[['/city/','В город'],['/sea/','В море']]);SW_UI.shell(title,body)}
 window.SW_ROUTER={render};
})();
